version: '3'

services:

  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ${APP_NAME}-django
    volumes:
      - ./backend:/app
    ports:
      - 8000:8000

  nginx:
    image: nginx:latest
    container_name: ${APP_NAME}-nginx
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./nginx/:/etc/nginx/templates/
      - ./certs:/etc/certs
    environment:
      - "NGINX_ENVSUBST_TEMPLATE_SUFFIX=.conf"
      - "DOMAIN=${DOMAIN}"
    depends_on:
      - web
    restart: always
  
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: ${APP_NAME}-frontend
    volumes:
      - ./frontend:/app
    ports:
      - 3000:3000
    depends_on:
      - web
    restart: always


# volumes: